(part "2MS1-T2-B4-M2-Q-E-S"
    (packageRef "2MS1T2B4M2QES")
    (interface
        (port "1" (symbPinId 1) (portName "NO") (portType INOUT))
        (port "2" (symbPinId 2) (portName "COM") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NC") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "RS_Part_Number" "")
    (property "RS_Price/Stock" "")
    (property "Manufacturer_Name" "Cosland")
    (property "Manufacturer_Part_Number" "2MS1-T2-B4-M2-Q-E-S")
    (property "Description" "2M SERIES SUBMINIATURE TOGGLE SWITCH")
    (property "Datasheet_Link" "http://www.kyohritsu.jp/eclib/OTHER/CATALOG/SW/2mseries.pdf")
    (property "symbolName1" "2MS1-T2-B4-M2-Q-E-S")
)
