(part "NJL7502R"
    (packageRef "NJL7502R")
    (interface
        (port "1" (symbPinId 1) (portName "C") (portType INOUT))
        (port "2" (symbPinId 2) (portName "E") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "RS_Part_Number" "")
    (property "RS_Price/Stock" "")
    (property "Manufacturer_Name" "New Japan Radio")
    (property "Manufacturer_Part_Number" "NJL7502R")
    (property "Description" "Ambient Light Sensor")
    (property "Datasheet_Link" "")
    (property "symbolName1" "NJL7502R")
)
