(part "NJM7805SDL1-TE1"
    (packageRef "NJM7805SDL1TE1")
    (interface
        (port "1" (symbPinId 1) (portName "VIN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "VOUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "RS_Part_Number" "2444523P")
    (property "RS_Price/Stock" "http://uk.rs-online.com/web/p/products/2444523P")
    (property "Manufacturer_Name" "Nisshinbo")
    (property "Manufacturer_Part_Number" "NJM7805SDL1-TE1")
    (property "Description" "Linear Voltage Regulator IC Positive Fixed 1 Output 1.5A TO-252-3")
    (property "Datasheet_Link" "http://uk.rs-online.com/web/p/products/2444523P")
    (property "symbolName1" "NJM7805SDL1-TE1")
)
