(part "PA4309_104NLT"
    (packageRef "PA4309104NLT")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Manufacturer_Name" "Yageo Group")
    (property "Manufacturer_Part_Number" "PA4309.104NLT")
    (property "Mouser_Part_Number" "673-PA4309.104NLT")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Pulse-Electronics/PA4309.104NLT?qs=MffrMO56dLbFdwJL%252B6MqkQ%3D%3D")
    (property "Arrow_Part_Number" "PA4309.104NLT")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/pa4309.104nlt/pulse-electronics-corporation?region=nac")
    (property "Description" "Inductor Power Unshielded Drum Core 100uH 20% 100KHz 3.5A 405mOhm DCR T/R")
    (property "Datasheet_Link" "https://productfinder.pulseelectronics.com/api/open/part-attachments/datasheet/PA4309.104NLT")
    (property "symbolName1" "PA4309_104NLT")
)
