(part "3557-15"
    (packageRef "355715")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "RS_Part_Number" "")
    (property "RS_Price/Stock" "")
    (property "Manufacturer_Name" "Keystone Electronics")
    (property "Manufacturer_Part_Number" "3557-15")
    (property "Allied_Number" "70914078")
    (property "Description" "Fuse Holder T/H 2 IN 1 AUTO BLDE HOLDER, BLUE 15A")
    (property "Datasheet_Link" "https://www.keyelco.com/product-pdf.cfm?p=14225")
    (property "symbolName1" "3557-15")
)
