(part "0527450897"
    (packageRef "0527450897")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "8" (symbPinId 8) (portName "8") (portType INOUT))
        (port "MP1" (symbPinId 9) (portName "MP1") (portType INOUT))
        (port "MP2" (symbPinId 10) (portName "MP2") (portType INOUT))
        (port "MP3" (symbPinId 11) (portName "MP3") (portType INOUT))
        (port "MP4" (symbPinId 12) (portName "MP4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "Molex")
    (property "Manufacturer_Part_Number" "0527450897")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "0527450897")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/0527450897/molex")
    (property "Description" "Easy-On FFC/FPC Connector, 0.50mm Pitch, Slider Series, Right-Angle, Top  Contact, 2.00mm Height, 8 Circuits, Gold Plating")
    (property "Datasheet_Link" "https://www.molex.com/en-us/products/part-detail-pdf/527450897?display=pdf")
    (property "symbolName1" "0527450897")
)
