(part "NJM7805SDL1-TE1"
    (packageRef "NJM7805SDL1TE1")
    (interface
        (port "1" (symbPinId 1) (portName "VIN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "VOUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Nisshinbo")
    (property "Manufacturer_Part_Number" "NJM7805SDL1-TE1")
    (property "Mouser_Part_Number" "513-NJM7805SDL1-TE1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Nisshinbo/NJM7805SDL1-TE1?qs=GBLSl2AkirtxkrsaOjZilw%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Linear Voltage Regulator IC Positive Fixed 1 Output 1.5A TO-252-3")
    (property "Datasheet_Link" "https://www.nisshinbo-microdevices.co.jp/ja/pdf/datasheet/NJM7800S_J.pdf")
    (property "symbolName1" "NJM7805SDL1-TE1")
)
