(part "NJL7502L"
    (packageRef "NJL7502L")
    (interface
        (port "1" (symbPinId 1) (portName "C") (portType INOUT))
        (port "2" (symbPinId 2) (portName "E") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Nisshinbo")
    (property "Manufacturer_Part_Number" "NJL7502L")
    (property "Mouser_Part_Number" "513-NJL7502L")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Nisshinbo/NJL7502L?qs=Vf9KeiGtj%252BH8dpWd%252B41FfA%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Ambient Light Sensors Ambient Light Sensor -40C to 85C ,70V,560 nm V,100 nA")
    (property "Datasheet_Link" "https://www.nisshinbo-microdevices.co.jp/en/pdf/datasheet/NJL7502L_E.pdf")
    (property "symbolName1" "NJL7502L")
)
