(part "TC33X-2-104E"
    (packageRef "TC33X2503E")
    (interface
        (port "1" (symbPinId 1) (portName "CCW") (portType INOUT))
        (port "2" (symbPinId 2) (portName "WIPER") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CW") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Marutsu_Elec_Corporation_Part_Number" "")
    (property "Marutsu_Elec_Corporation_Price/Stock" "")
    (property "Manufacturer_Name" "Bourns")
    (property "Manufacturer_Part_Number" "TC33X-2-104E")
    (property "Description" "Cermet 3mm SMT trimmer,0.1W 100k Bourns TC33 Series SMD Cermet Trimmer Resistor with Solder Pad Terminations, 100k +/-25% 1/10W +/-250ppm/C Top Adjust")
    (property "Datasheet_Link" "https://www.bourns.com/pdfs/TC33.pdf")
    (property "symbolName1" "TC33X-2-104E")
)
