(part "CSD18540Q5B"
    (packageRef "CSD18540Q5B")
    (interface
        (port "1" (symbPinId 1) (portName "S_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "S_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "S_3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "G") (portType INOUT))
        (port "5" (symbPinId 5) (portName "D_1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "D_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "D_3") (portType INOUT))
        (port "8" (symbPinId 8) (portName "D_4") (portType INOUT))
        (port "9" (symbPinId 9) (portName "D_5") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "RS_Part_Number" "")
    (property "RS_Price/Stock" "")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "CSD18540Q5B")
    (property "Description" "MOSFET 60V, N-channel NexFET Pwr MOSFET")
    (property "Datasheet_Link" "https://www.ti.com/lit/ds/symlink/csd18540q5b.pdf?ts=1669951210192&ref_url=https%253A%252F%252Fcomponentsearchengine.com%252F")
    (property "symbolName1" "CSD18540Q5B")
)
