(part "TVGP01-G73BB"
    (packageRef "TVGP01G73BB")
    (interface
        (port "1" (symbPinId 1) (portName "COM_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "COM_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NO_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NO_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "RS_Part_Number" "")
    (property "RS_Price/Stock" "")
    (property "Manufacturer_Name" "Zhejiang Jianfu Electronics Co., Ltd")
    (property "Manufacturer_Part_Number" "TVGP01-G73BB")
    (property "Description" "Tactile Switch")
    (property "Datasheet_Link" "http://akizukidenshi.com/download/ds/jianfu/TVGP01-G73BB.pdf")
    (property "symbolName1" "TVGP01-G73BB")
)
