(part "NJM2391DL1-33-TE1"
    (packageRef "TO-252-3-L1")
    (interface
        (port "1" (symbPinId 1) (portName "VIN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VOUT") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "RS_Part_Number" "2444497")
    (property "RS_Price/Stock" "http://uk.rs-online.com/web/p/products/2444497")
    (property "Manufacturer_Name" "New Japan Radio")
    (property "Manufacturer_Part_Number" "NJM2391DL1-33-TE1")
    (property "Description" "LDO Voltage Regulators LDO")
    (property "Datasheet_Link" "http://uk.rs-online.com/web/p/products/2444497")
    (property "symbolName1" "NJM2391DL1-33-TE1")
)
